---
title: "Otchet"
author: "Olya Shirokova"
date: '29 марта 2017 г '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Отчёт по выполненым заданиям
### Задание 1

```{r iris}
iris
iris$Sepal.Length
mean(iris$Sepal.Length)
x=mean(iris$Sepal.Length)
x
iris$Sepal.Width
mean(iris$Sepal.Width)
y=mean(iris$Sepal.Width)
y
iris$Petal.Length
mean(iris$Petal.Length)
z=mean(iris$Petal.Length)
z
iris$Petal.Width
mean(iris$Petal.Width)
h=mean(iris$Petal.Width)
h
list(x,y,x,h)
length(list(x,y,x,h))
```

### Задание 2

```{r iris 2}
iris
y = c()
for (i in 1:150)
{x = sum(iris[i,1:4]/4) 
y = c(x,y)}
y
```



### Задание 3

```{r DNA}
DNA = c("A","G","T","C")
DNA=summary(DNA, size = 1000, replece=T)
DNA=factor(DNA)
summary(DNA)/length(DNA)
dna_at=c(DNA[1],DNA[4]); dna_at
dna_at
```

### Задание 4

```{r letters}
knitr::kable(head(letters))
letters 
abc=sample(letters, size=10000, replace=T) 
knitr::kable(head(abc))
for(i in length(abc)) 
  if(abc[i]=="a"|abc[i]=="e"|abc[i]=="i"|abc[i]=="o"|abc[i]=="u"|abc[i]=="y") 
  {vowel=y+1} 
"else{vowel+0}" 
'vowel'
```

### Задание 5

```{r,}
knitr::kable(head(iris))
names(iris)
iris$Petal.Length
setosa=c(iris$Petal.Length[1:50])
setosa
versicolor=c(iris$Petal.Length[51:100])
versicolor
virginica=c(iris$Petal.Length[101:150])
mean(setosa)
mean(versicolor)
mean(virginica)
Species=c(mean(setosa),mean(versicolor),mean(virginica))
sort(Species)
f=factor(sort(Species))
f
names(f)<- c("setosa", "versicolor", "virginica")
f
```

### Задание 6

```{r}
median <- function(x) { 
z=sort(x) 
if((length(z)%%2)!=0){ 
result = z[(length(x)/2)+1] 
} 
else 
result = (z[length(x)/2]+z[length(x)/2+1])/2 
return(result) 
}
median(iris$Sepal.Length)

```

### Задание 7

```{r}
knitr::kable(head(iris))
names(iris)
x=iris$Sepal.Length[1:50]
y=iris$Petal.Length[1:50]
plot(x,y,main="The dependence of the length of the sepal length of petal to form setosa", xlab="Sepal.Length",ylab="$Petal.Length", col="purple")
x=NULL
y=NULL
x=iris$Sepal.Length[51:101]
y=iris$Petal.Length[51:101]
plot(x,y,main="The dependence of the length of the sepal length of petal to form versicolor", xlab="Sepal.Length",ylab="$Petal.Length", col="red")
x=NULL
y=NULL
x=iris$Sepal.Length[101:150]
y=iris$Petal.Length[101:150]
plot(x,y,main="The dependence of the length of the sepal length of petal to form virginica", xlab="Sepal.Length",ylab="$Petal.Length", col="orange")
x=NULL
y=NULL

```

### Задание 8

```{r}
library(ggplot2)
knitr::kable(head(diamonds))
tapply(diamonds$price[diamonds$price >1000], diamonds$clarity[diamonds$price >1000], mean)
```

### Задание 9 и 10

```{r}
help_Spirmen=function(table,ind)
{
  table=table[order(table[,ind]),]
  table[,ind+2]=1:nrow(table)
  line=table[,ind]
  for (i in as.numeric(names(table(line)[table(line)>1]))){
    sum=0
    for (j in which(line %in% i))
    {
      sum=sum+table[j,ind+2]
    }
    sum=sum/length(which(line %in% i))
    table[which(line %in% i),ind+2]=sum
  }
  return(table)
}
Spirmen=function(x1,x2)
{
  if(length(x1)!=length(x2))
  {
    return("Problem with the lengths of the vectors")
  }
  table=matrix(ncol=5,nrow=length(x1))
  table[,1]=x1
  table[,2]=x2
  table=help_Spirmen(table,1)
  table=help_Spirmen(table,2)
  table[,5]=(table[,3]-table[,4])**2
  sum=sum(table[,5])
  result=1-6*sum/(length(x1)*(length(x1)**2-1))
  return(result)  
}
med=function(elements)
{
  elements=elements[order(elements)]
  if(length(elements)%%2==0)
  {
    n=length(elements)%/%2
    element=(elements[n]+elements[n+1])/2
  }
  else
  {
    element=elements[length(elements)%/%2+1]
  }
  return(element)
}

```

```{r}
library("tidyverse") 
library("nycflights13") 
library("tidyr") 
library("stringr") 
library("dplyr") 
library("tibble") 
library("readr") 
tbl = read_csv("https://www.dropbox.com/s/erhs9hoj4vhrz0b/eddypro.csv?dl=1", skip = 1, na =c("","NA","-9999","-9999.0"), comment=c("[")) 
tbl = tbl[-1,] 
tbl 
glimpse(tbl) 
tbl = select(tbl, -(roll)) 
tbl = tbl %>% mutate_if(is.character, factor) 
#names(tbl) = str_replace_all(names(tbl), "[!]","_emph_") 
names(tbl) = names(tbl) %>% 
str_replace_all("[!]","_emph_") %>% 
str_replace_all("[?]","_quest_") %>% 
str_replace_all("[*]","_star_") %>% 
str_replace_all("[+]","_plus_") %>% 
str_replace_all("[@]","_at_") %>% 
str_replace_all("[-]","_minus_") %>% 
str_replace_all("[$]","_dollar_") %>% 
str_replace_all("[#]","_hash_") %>% 
str_replace_all("[/]","_div_") %>% 
str_replace_all("[%]","_perc_") %>% 
str_replace_all("[&]","_amp_") %>% 
str_replace_all("[\\^]","_power_") %>% 
str_replace_all("[()]","_") 
glimpse(tbl) 
sapply(tbl,is.numeric) 
tbl_numeric = tbl[,sapply(tbl,is.numeric)] 
tbl_non_numeric = tbl[,!sapply(tbl,is.numeric) ] 
tbl_numeric <- drop_na(tbl_numeric) 
names(tbl_numeric) 

cor_td = cor(drop_na(tbl_numeric)) %>% as.data.frame %>% select(co2_flux) 
vars = row.names(cor_td)[cor_td$co2_flux^2 > .1] %>% na.exclude 
formula = as.formula(paste("co2_flux~", paste(vars,collapse = "+"), sep="")) 
 
teaching_tbl = sample_n(tbl, floor(length(tbl$date)*.7)) 
testing_tbl = sample_n(tbl, floor(length(tbl$date)*.3)) 
tbl_numeric = filter(tbl_numeric, DOY > 151) 
tbl_numeric = filter(tbl_numeric, DOY < 243) 
mod = lm(co2_flux ~ (Tau+rand_err_Tau+H+rand_err_H+LE+qc_LE+rand_err_LE+co2_flux+h2o_flux+qc_h2o_flux+rand_err_h2o_flux+H_strg+co2_molar_density+h2o_time_lag+sonic_temperature+air_temperature+air_density+air_molar_volume+es+RH+VPD+max_speed+u_star_+TKE+T_star_+un_Tau+un_H+un_LE+un_co2_flux+un_h2o_flux+u_var+v_var+w_var+h2o_var+w_div_ts_cov+w_div_co2_cov+w_div_h2o_cov+flowrate)^2, data = tbl_numeric) 
summary(mod) 
resid(mod) 
coef(mod) 
names(tbl_numeric) 
qplot(co2_flux, DOY, data = tbl_numeric, alpha = I(1/10)) + theme_bw() + geom_line(aes(y = predict(mod))) 
qplot(co2_flux, predict(mod), data = tbl_numeric, geom = "line") 
qplot(flowrate, co2_flux, data = tbl_numeric, alpha = I(1/10)) + theme_bw() + geom_line(aes(y = predict(mod))) 
#lm(earn ~ . - age, data = wages) 
anova(mod)
```